class UdpBus:
    """
    A UDP socket communication bus
    """

    def __init__(self, host, port, /) -> None: ...
    def bind(self, /): ...
    def set_recv_timeout(self, seconds, /): ...
    def send_to(self, data, host, port, /): ...
    def recv(self, /, *, buffer_size=1024): ...
    def recv_from(self, /, *, buffer_size=1024): ...
